name: spot-quality

on:
  push:  
  pull_request:

jobs:
  ci-check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          default: true
          components: rustfmt

      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  shellcheck:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: |
            sudo apt-get -y update && sudo apt-get -y install shellcheck
            find $GITHUB_WORKSPACE -type f -and \( -name "*.sh" \) | xargs shellcheck
